### ISSUE TITLE
Esp8266, does it work?

### ISSUE THREAD

**Issue by marksev1** [ruralguru/ERW_MSGEQ7#1]
Does this library work on the Esp8266?

Also could you please help me how I could use this library to turn on neopixels? Just some basic stuff which command I should use, to get me started.

**Comment by ruralguru** [comment]
the lights run using the fastled library at fastled.io

**Comment by ruralguru** [comment]
My past response was junk and I apologize.

Make sure you have a 7 int long array for each channel. I chose int leftAmplitudes[7] and rightAmplitudes[7]

You need the 4 variables to initialize the setup.  I chose leftRead, rightRead, Strobe, and Reset.
To initialize the class use: VU.begin(leftRead, rightRead, Strobe, Reset)
To fill the arrays run  VU.getAmplitudes(leftAmplitudes, rightAmplitudes)
The array holds the following frequencies in the following orde as ADC reads: 63Hz, 160Hz, 400Hz, 1kHz, 2.5kHz, 6.25kHz, and 16kHz.

Only tested with Arduino
